highlighter: pygments
#lsi: true
permalink: pretty
base_url: ""
rdiscount:
  extensions: []
markdown: rdiscount
paginate: 10
future: false

exclude: [
    tasks
]

# user defined variables
auto_excerpt_length: 20

